-- ARCHIVO GENERADO por scripts/generar-catalogo.mjs. No editar a mano.
-- Generado a partir del contenido de src/data/. 63 actividades.

begin;

insert into public.estaciones (id, orden, titulo, sesion) values
  ('proceso', 1, 'Cómo se construye el software', 'Sesión 7'),
  ('calidad', 2, '¿Cuándo un software es bueno?', 'Sesión 8'),
  ('robustez', 3, 'Que no se rompa', 'Sesión 9'),
  ('tic', 4, 'Informática y sociedad', 'Sesiones 8 y 9'),
  ('paradigmas', 5, 'Pensar como programador', 'Sesión 10'),
  ('reto-final', 6, 'Reto final de práctica', 'Preparación sesión 11')
on conflict (id) do update set orden = excluded.orden, titulo = excluded.titulo, sesion = excluded.sesion;

insert into public.actividades (id, estacion_id, titulo, tipo, nivel, puntos_max, cuenta_nota, conceptos, orden) values
  ('e1-a1-orden', 'proceso', 'Ordena el desarrollo', 'orden', 'base', 100, true, ARRAY['proceso', 'requisito', 'iteracion']::text[], 0),
  ('e1-a2-roles', 'proceso', '¿Quién se encarga?', 'emparejar', 'base', 100, true, ARRAY['rol', 'proceso']::text[], 1),
  ('e1-a3-requisitos', 'proceso', 'Requisito o frase vaga', 'clasificar', 'base', 120, true, ARRAY['requisito', 'verificable', 'restriccion']::text[], 2),
  ('e1-a4-entrega', 'proceso', 'Construye una entrega', 'entrega', 'base', 120, true, ARRAY['alcance-minimo', 'incremento', 'requisito']::text[], 3),
  ('e1-a5-cambio', 'proceso', 'Llegó un cambio', 'caso', 'base', 100, true, ARRAY['proceso', 'iteracion', 'actividad-sombrilla']::text[], 4),
  ('e1-a6-modelos', 'proceso', 'Mitos sobre los modelos de proceso', 'vf', 'opcional', 90, false, ARRAY['proceso', 'iteracion']::text[], 5),
  ('e1-a7-velocidad', 'proceso', 'Proyectar con velocidad', 'calcular', 'opcional', 90, false, ARRAY['iteracion', 'incremento']::text[], 6),
  ('e1-reto:p1', 'proceso', 'Del problema al primer incremento · paso 1', 'quiz', 'base', 38, true, ARRAY['proceso']::text[], 7),
  ('e1-reto:p2', 'proceso', 'Del problema al primer incremento · paso 2', 'quiz', 'base', 38, true, ARRAY['verificable', 'requisito']::text[], 8),
  ('e1-reto:p3', 'proceso', 'Del problema al primer incremento · paso 3', 'entrega', 'base', 37, true, ARRAY['alcance-minimo', 'incremento']::text[], 9),
  ('e1-reto:p4', 'proceso', 'Del problema al primer incremento · paso 4', 'caso', 'base', 37, true, ARRAY['actividad-sombrilla', 'finalidad']::text[], 10),
  ('e1-taller', 'proceso', 'Taller en clase · Un problema del campus', 'taller', 'base', 0, false, '{}'::text[], 11),
  ('e2-a1-detective', 'calidad', 'Detective de calidad', 'clasificar', 'base', 120, true, ARRAY['calidad', 'adecuacion-funcional', 'usabilidad', 'square']::text[], 0),
  ('e2-a2-friccion', 'calidad', 'Encuentra la fricción', 'formulario-friccion', 'base', 120, true, ARRAY['usabilidad', 'calidad']::text[], 1),
  ('e2-a3-mejora', 'calidad', 'Mejora la interfaz', 'mejora-interfaz', 'base', 110, true, ARRAY['usabilidad']::text[], 2),
  ('e2-a4-medir', 'calidad', 'Mide la usabilidad', 'calcular', 'base', 130, true, ARRAY['usabilidad', 'tasa-exito']::text[], 3),
  ('e2-a5-probar', 'calidad', '¿Qué probarías?', 'emparejar', 'base', 110, true, ARRAY['verificable', 'calidad', 'usabilidad']::text[], 4),
  ('e2-a6-square', 'calidad', 'Ubicar la norma', 'quiz', 'opcional', 80, false, ARRAY['square']::text[], 5),
  ('e2-a7-subcaracteristicas', 'calidad', 'Cada subcaracterística en su lugar', 'clasificar', 'opcional', 90, false, ARRAY['square', 'usabilidad', 'portabilidad']::text[], 6),
  ('e2-reto:p1', 'calidad', 'Diagnóstico de calidad de una app real · paso 1', 'emparejar', 'base', 38, true, ARRAY['calidad', 'adecuacion-funcional']::text[], 7),
  ('e2-reto:p2', 'calidad', 'Diagnóstico de calidad de una app real · paso 2', 'quiz', 'base', 38, true, ARRAY['calidad', 'datos-personales']::text[], 8),
  ('e2-reto:p3', 'calidad', 'Diagnóstico de calidad de una app real · paso 3', 'calcular', 'base', 37, true, ARRAY['tasa-exito', 'usabilidad']::text[], 9),
  ('e2-reto:p4', 'calidad', 'Diagnóstico de calidad de una app real · paso 4', 'quiz', 'base', 37, true, ARRAY['usabilidad', 'calidad-en-uso']::text[], 10),
  ('e2-taller', 'calidad', 'Taller en clase · Auditoría de una app conocida', 'taller', 'base', 0, false, '{}'::text[], 11),
  ('e3-a1-romper', 'robustez', 'Rompe el formulario', 'romper-formulario', 'base', 140, true, ARRAY['robustez', 'validacion', 'frontera', 'defecto']::text[], 0),
  ('e3-a2-limites', 'robustez', 'Explora los límites', 'limites', 'base', 110, true, ARRAY['frontera', 'validacion']::text[], 1),
  ('e3-a3-compatible', 'robustez', '¿Compatible o portable?', 'clasificar', 'base', 110, true, ARRAY['compatibilidad', 'portabilidad', 'disponibilidad']::text[], 2),
  ('e3-a4-conexion', 'robustez', 'Se cayó la conexión', 'caso', 'base', 110, true, ARRAY['robustez', 'disponibilidad']::text[], 3),
  ('e3-a5-tabla', 'robustez', 'Diseña las pruebas', 'tabla-pruebas', 'base', 130, true, ARRAY['frontera', 'validacion', 'defecto']::text[], 4),
  ('e3-a6-disponibilidad', 'robustez', 'Cuánto es un nueve más', 'calcular', 'opcional', 90, false, ARRAY['disponibilidad']::text[], 5),
  ('e3-a7-reporte', 'robustez', 'Anatomía de un reporte de defecto', 'orden', 'opcional', 80, false, ARRAY['defecto']::text[], 6),
  ('e3-reto:p1', 'robustez', 'Poner a prueba una función nueva · paso 1', 'limites', 'base', 38, true, ARRAY['frontera', 'validacion']::text[], 7),
  ('e3-reto:p2', 'robustez', 'Poner a prueba una función nueva · paso 2', 'quiz', 'base', 38, true, ARRAY['defecto', 'validacion']::text[], 8),
  ('e3-reto:p3', 'robustez', 'Poner a prueba una función nueva · paso 3', 'caso', 'base', 37, true, ARRAY['defecto']::text[], 9),
  ('e3-reto:p4', 'robustez', 'Poner a prueba una función nueva · paso 4', 'vf', 'base', 37, true, ARRAY['robustez', 'frontera']::text[], 10),
  ('e3-taller', 'robustez', 'Taller en clase · Reporte de defecto', 'taller', 'base', 0, false, '{}'::text[], 11),
  ('e4-a1-simulador', 'tic', 'Simulador de duplicación', 'simulador-moore', 'base', 110, true, ARRAY['exponencial', 'ley-de-moore']::text[], 0),
  ('e4-a2-predice', 'tic', 'Predice antes de mover', 'predice', 'base', 110, true, ARRAY['exponencial']::text[], 1),
  ('e4-a3-mitos', 'tic', 'Mito o conclusión válida', 'vf', 'base', 120, true, ARRAY['ley-de-moore', 'exponencial']::text[], 2),
  ('e4-a4-todos', 'tic', 'Diseña para todos', 'entrega', 'base', 120, true, ARRAY['brecha-digital', 'accesibilidad']::text[], 3),
  ('e4-a5-datos', 'tic', '¿Necesitas ese dato?', 'datos-necesarios', 'base', 130, true, ARRAY['datos-personales', 'finalidad']::text[], 4),
  ('e4-a6-leyes', 'tic', 'Protección de datos o delito informático', 'clasificar', 'opcional', 100, false, ARRAY['datos-personales', 'finalidad']::text[], 5),
  ('e4-reto:p1', 'tic', 'Un servicio digital para todo el campus · paso 1', 'calcular', 'base', 38, true, ARRAY['exponencial']::text[], 6),
  ('e4-reto:p2', 'tic', 'Un servicio digital para todo el campus · paso 2', 'entrega', 'base', 38, true, ARRAY['brecha-digital', 'accesibilidad']::text[], 7),
  ('e4-reto:p3', 'tic', 'Un servicio digital para todo el campus · paso 3', 'datos-necesarios', 'base', 37, true, ARRAY['finalidad', 'datos-personales']::text[], 8),
  ('e4-reto:p4', 'tic', 'Un servicio digital para todo el campus · paso 4', 'quiz', 'base', 37, true, ARRAY['datos-personales', 'finalidad']::text[], 9),
  ('e4-taller', 'tic', 'Taller en clase · Un servicio digital del campus', 'taller', 'base', 0, false, '{}'::text[], 10),
  ('e5-a1-traza', 'paradigmas', 'Sigue las variables', 'traza', 'base', 110, true, ARRAY['variable', 'asignacion', 'contador', 'acumulador']::text[], 0),
  ('e5-a2-armar', 'paradigmas', 'Arma el algoritmo', 'algoritmo', 'base', 130, true, ARRAY['algoritmo', 'contador', 'variable']::text[], 1),
  ('e5-a3-decision', 'paradigmas', 'Completa la decisión', 'completar', 'base', 120, true, ARRAY['algoritmo', 'frontera']::text[], 2),
  ('e5-a4-ciclo', 'paradigmas', 'Repara el ciclo', 'pseudo', 'base', 120, true, ARRAY['algoritmo', 'contador', 'acumulador']::text[], 3),
  ('e5-a5-contador', 'paradigmas', 'Contador o acumulador', 'completar', 'base', 130, true, ARRAY['contador', 'acumulador', 'variable']::text[], 4),
  ('e5-a6-objetos', 'paradigmas', 'Del objeto a la clase', 'clase-objeto', 'base', 120, true, ARRAY['clase', 'objeto', 'atributo', 'metodo']::text[], 5),
  ('e5-a7-centinela', 'paradigmas', 'Lectura con centinela', 'pseudo', 'opcional', 130, false, ARRAY['centinela', 'acumulador', 'contador']::text[], 6),
  ('e5-reto', 'paradigmas', 'Reto integrador · Informe de notas', 'pseudo', 'base', 170, true, ARRAY['algoritmo', 'contador', 'acumulador', 'variable']::text[], 7),
  ('e5-taller', 'paradigmas', 'Taller en clase · Tu algoritmo, explicado', 'taller', 'base', 0, false, '{}'::text[], 8),
  ('e6-reto-final:f1', 'reto-final', 'Caso completo: préstamo de equipos del laboratorio · paso 1', 'quiz', 'base', 100, true, ARRAY['requisito']::text[], 0),
  ('e6-reto-final:f2', 'reto-final', 'Caso completo: préstamo de equipos del laboratorio · paso 2', 'clasificar', 'base', 100, true, ARRAY['verificable', 'restriccion']::text[], 1),
  ('e6-reto-final:f3', 'reto-final', 'Caso completo: préstamo de equipos del laboratorio · paso 3', 'emparejar', 'base', 100, true, ARRAY['calidad', 'usabilidad', 'adecuacion-funcional']::text[], 2),
  ('e6-reto-final:f4', 'reto-final', 'Caso completo: préstamo de equipos del laboratorio · paso 4', 'limites', 'base', 100, true, ARRAY['frontera', 'validacion']::text[], 3),
  ('e6-reto-final:f5', 'reto-final', 'Caso completo: préstamo de equipos del laboratorio · paso 5', 'pseudo', 'base', 100, true, ARRAY['algoritmo', 'contador', 'acumulador']::text[], 4),
  ('e6-reto-final:f6', 'reto-final', 'Caso completo: préstamo de equipos del laboratorio · paso 6', 'caso', 'base', 100, true, ARRAY['finalidad', 'accesibilidad', 'datos-personales']::text[], 5),
  ('laboratorio', 'paradigmas', 'Laboratorio de pseudocódigo', 'laboratorio', 'base', 0, false, '{}'::text[], 99)
on conflict (id) do update set
  estacion_id = excluded.estacion_id,
  titulo      = excluded.titulo,
  tipo        = excluded.tipo,
  nivel       = excluded.nivel,
  puntos_max  = excluded.puntos_max,
  cuenta_nota = excluded.cuenta_nota,
  conceptos   = excluded.conceptos,
  orden       = excluded.orden;

insert into public.logros (id, titulo, descripcion, evidencia) values
  ('primer-dominio', 'Sin pistas', 'Resolviste una actividad al primer intento y sin abrir pistas.', 'Al menos una actividad en estado "dominio demostrado".'),
  ('estacion-1-completa', 'El proceso, entendido', 'Completaste todas las actividades base de la estación 1.', 'Todas las actividades de nivel base de la estación 1, completadas.'),
  ('estacion-2-completa', 'Criterio de calidad', 'Completaste todas las actividades base de la estación 2.', 'Todas las actividades de nivel base de la estación 2, completadas.'),
  ('estacion-3-completa', 'A prueba de usuarios', 'Completaste todas las actividades base de la estación 3.', 'Todas las actividades de nivel base de la estación 3, completadas.'),
  ('estacion-4-completa', 'Con los pies en la tierra', 'Completaste todas las actividades base de la estación 4.', 'Todas las actividades de nivel base de la estación 4, completadas.'),
  ('estacion-5-completa', 'Pensamiento algorítmico', 'Completaste todas las actividades base de la estación 5.', 'Todas las actividades de nivel base de la estación 5, completadas.'),
  ('algoritmo-ejecutado', 'Tu algoritmo corre', 'Escribiste un algoritmo que pasó todos sus casos de prueba, incluidos los límites.', 'Una actividad de pseudocódigo completada.'),
  ('tres-algoritmos', 'Ya no es suerte', 'Tres algoritmos distintos pasando sus casos de prueba.', 'Tres actividades de pseudocódigo o de armado de algoritmos, completadas.'),
  ('sin-ayuda', 'Racha limpia', 'Cinco actividades con dominio demostrado.', 'Cinco actividades en estado "dominio demostrado".'),
  ('ruta-completa', 'Ruta principal terminada', 'Completaste las actividades base de las cinco estaciones de contenido.', 'Estaciones 1 a 5 con su nivel base completo.'),
  ('desafios-opcionales', 'Fuiste más allá', 'Resolviste cinco desafíos opcionales.', 'Cinco actividades de nivel opcional, completadas.'),
  ('reto-final', 'Listo para el parcial', 'Terminaste el reto final de práctica con al menos el 70 % del puntaje.', 'Puntaje del reto final ≥ 70 % de su máximo.')
on conflict (id) do update set titulo = excluded.titulo, descripcion = excluded.descripcion, evidencia = excluded.evidencia;

commit;
